### ISSUE TITLE
Compilation error in samples/spheres3D/source/main.c 

### ISSUE THREAD

**Issue by NortheLo** [wargio/tiny3D#17]
The build fails with the following compilations error:
```
home/louis/Documents/ps3/tiny3D/samples/spheres3D/source/main.c: In function 'LoadTexture':
/home/louis/Documents/ps3/tiny3D/samples/spheres3D/source/main.c:262:41: error: 'texture1_png_bin_size' undeclared (first use in this function); did you mean 'texture1_png_bin_end'?
     pngLoadFromBuffer(texture1_png_bin, texture1_png_bin_size, &texture1);
                                         ^~~~~~~~~~~~~~~~~~~~~
                                         texture1_png_bin_end
/home/louis/Documents/ps3/tiny3D/samples/spheres3D/source/main.c:262:41: note: each undeclared identifier is reported only once for each function it appears in
/home/louis/Documents/ps3/tiny3D/samples/spheres3D/source/main.c:263:41: error: 'texture2_png_bin_size' undeclared (first use in this function); did you mean 'texture1_png_bin_size'?
     pngLoadFromBuffer(texture2_png_bin, texture2_png_bin_size, &texture2);
                                         ^~~~~~~~~~~~~~~~~~~~~
                                         texture1_png_bin_size
make[3]: *** [/home/louis/Documents/ps3/ps3toolchain/bin/base_rules:68: main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:125: build] Error 2
make[1]: *** [Makefile:9: all] Error 2
make: *** [Makefile:8: all] Error 2
```

Edit: After some investigation, I have found that the sample itself can be build with its Makefile and works correctly in rpcs3. I am guessing right now, that the linker can't find the binary to link, because the path to the ressource is different from the projects directory instead from the sample directory. But thats just a speculation, I keep investigating.

**Comment by wargio** [comment]
it's possible the sdk got updated and some old scripts don't work anymore. if you find the issue, feel free to submit a patch for it :)

**Comment by NortheLo** [comment]
As stupid as it sounds. Today i just cleaned the project and recompiled it and  now it works.
Diff shows, that i havent made any changes and my bash history isnt insightful either ¯\_(ツ)_/¯
Thx and if i encounter the problem, i'll submit a patch, promise :D

**Comment by NortheLo** [comment]
As stupid as it sounds. Today i just cleaned the project and recompiled it and  now it works.
Diff shows, that i havent made any changes and my bash history isnt insightful either ¯\_(ツ)_/¯
Thx and if i encounter the problem, i'll submit a patch, promise :D

**Comment by wargio** [comment]
if you want you can always close this.
