### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by DarkBattle0000** [wargio/tiny3D#18]
I'm having trouble trying to compile, it always returns me an error related to loading a library that says it's invalid

/home/dark/Tools/tiny3D/samples/fireworks3D/source/main.c:52:10: fatal error: spu_soundmodule_bin.h: No such file or directory
 #include "spu_soundmodule_bin.h" // load SPU Module
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by wargio** [comment]
you need this: https://github.com/wargio/ps3soundlib
