### ISSUE TITLE
Rename libfont to libfont3d as it collides with the SPRX version provided by the FW.

### ISSUE THREAD

**Issue by shagkur** [wargio/tiny3D#9]
For a project i'm working on, i added the font engine support from the FW. Those libraries added are (and should be) called libfont, libfontFT. Now since tiny3d also provides a small font library i'd request to rename this library to libfont3d.

**Comment by shagkur** [comment]
Here the PR: https://github.com/wargio/tiny3D/pull/10

**Comment by wargio** [comment]
renamed the lib, time to double check the samples

**Comment by wargio** [comment]
i think i fixed all the makefiles.
